framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command.bus
        buses:
            query.bus:
                middleware: ~
            command.bus:
                middleware: ~
            event.bus:
                default_middleware: allow_no_handlers
                middleware: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            in-memory: 'in-memory://'

        routing:
            # Route your messages to the transports
            '*': sync
